services:
  audiobook-downloader:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: audiobook-downloader
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
    ports:
      - "8000:8000"
    volumes:
      - ./Audiobooks:/app/Audiobooks
    restart: unless-stopped
